//! Which files should fold out of the way by default (issue #21,
//! BLUEPRINT §3.5): lockfiles and generated bundles dominate agent diffs
//! by line count while carrying no review signal.
//!
//! Pure, dependency-free, and deliberately conservative: a false negative
//! costs a keystroke (`za`), a false positive hides real code — so only
//! patterns that are generated by near-universal convention are here.
//! User- and repo-level `collapse` globs extend this list via config.

/// Should this path be collapsed by default?
///
/// Matches the well-known lockfile names, minified/bundled artifacts,
/// and the most common generated-code suffixes (a pragmatic subset of
/// GitHub's linguist-generated rules).
pub fn is_generated(path: &[u8]) -> bool {
    let Some(name) = basename(path) else {
        return false;
    };
    // Exact lockfile / checksum-file names.
    const NAMES: &[&[u8]] = &[
        b"Cargo.lock",
        b"package-lock.json",
        b"yarn.lock",
        b"pnpm-lock.yaml",
        b"bun.lockb",
        b"composer.lock",
        b"Gemfile.lock",
        b"poetry.lock",
        b"uv.lock",
        b"flake.lock",
        b"go.sum",
        b"Package.resolved",
    ];
    if NAMES.contains(&name) {
        return true;
    }
    // Generated-artifact suffixes.
    const SUFFIXES: &[&[u8]] = &[
        b".min.js",
        b".min.css",
        b".map",   // source maps
        b".pb.go", // protobuf codegen
        b".pb.rs",
        b"_pb2.py",
        b"_pb2_grpc.py",
        b".generated.cs",
        b".designer.cs",
        b".g.dart",
        b".freezed.dart",
    ];
    SUFFIXES.iter().any(|s| ends_with_ignore_case(name, s))
}

/// Minimal glob match for the `collapse` config key: `*` matches within
/// a path segment, `**` across segments, `?` one non-separator byte.
/// Matching is byte-wise on the repo-relative path; a pattern without a
/// slash matches against the basename (like `.gitignore`).
pub fn glob_match(pattern: &str, path: &[u8]) -> bool {
    let target: &[u8] = if pattern.as_bytes().contains(&b'/') {
        path
    } else {
        basename(path).unwrap_or(path)
    };
    glob_bytes(pattern.as_bytes(), target)
}

fn glob_bytes(pattern: &[u8], text: &[u8]) -> bool {
    match pattern.split_first() {
        None => text.is_empty(),
        Some((b'*', rest)) => {
            // `**` crosses separators; `*` stops at them.
            let (crosses, rest) = match rest.split_first() {
                Some((b'*', tail)) => (true, tail),
                _ => (false, rest),
            };
            let mut remainder = text;
            loop {
                if glob_bytes(rest, remainder) {
                    return true;
                }
                match remainder.split_first() {
                    Some((&b, tail)) if crosses || b != b'/' => remainder = tail,
                    _ => return false,
                }
            }
        }
        Some((b'?', rest)) => match text.split_first() {
            Some((&b, tail)) if b != b'/' => glob_bytes(rest, tail),
            _ => false,
        },
        Some((&p, rest)) => match text.split_first() {
            Some((&b, tail)) if b == p => glob_bytes(rest, tail),
            _ => false,
        },
    }
}

fn basename(path: &[u8]) -> Option<&[u8]> {
    path.rsplit(|&b| b == b'/').next()
}

fn ends_with_ignore_case(name: &[u8], suffix: &[u8]) -> bool {
    name.len() >= suffix.len() && name[name.len() - suffix.len()..].eq_ignore_ascii_case(suffix)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lockfiles_and_generated_artifacts_fold() {
        for path in [
            "Cargo.lock",
            "frontend/package-lock.json",
            "deep/nested/yarn.lock",
            "go.sum",
            "dist/app.min.js",
            "styles/site.min.css",
            "build/bundle.js.map",
            "api/service.pb.go",
            "proto/gen_pb2.py",
        ] {
            assert!(is_generated(path.as_bytes()), "{path} should fold");
        }
    }

    #[test]
    fn real_code_never_folds_by_default() {
        for path in [
            "src/main.rs",
            "Cargo.toml",
            "lock.rs", // contains "lock" but is code
            "src/lockfree.rs",
            "docs/map.md", // .md, not .map
            "unlocked.go",
        ] {
            assert!(!is_generated(path.as_bytes()), "{path} must not fold");
        }
    }

    #[test]
    fn glob_semantics() {
        // Basename matching when the pattern has no slash.
        assert!(glob_match("*.snap", b"tests/snapshots/ui__help.snap"));
        assert!(glob_match("*.lock", b"vendor/thing.lock"));
        assert!(!glob_match("*.snap", b"src/snap.rs"));
        // Path-aware when it does.
        assert!(glob_match("generated/*", b"generated/api.rs"));
        assert!(
            !glob_match("generated/*", b"generated/sub/api.rs"),
            "single star stops at separators"
        );
        assert!(glob_match("generated/**", b"generated/sub/api.rs"));
        assert!(glob_match("**/dist/*.js", b"pkg/a/dist/bundle.js"));
        // `?` is one non-separator byte.
        assert!(glob_match("v?.rs", b"v1.rs"));
        assert!(!glob_match("v?.rs", b"v12.rs"));
        assert!(!glob_match("a?b", b"a/b"));
    }
}
